# Header
menu:
  Home: /
  Archives: /archives
  Canvas-Examples: /2020/03/23/canvas-example/
  Github : https://github.com/dustinpfister
  About : /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-83195184-1
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:

# phaser
phaser:
  enabled : true